version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "9825:9825"
    environment:
      - NODE_ENV=development
    volumes:
      - ../backend:/app/backend
      - ../shared:/app/shared
    depends_on:
      - database

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ../frontend:/app/frontend
      - ../shared:/app/shared

  database:
    image: alpine:latest
    volumes:
      - ../data:/data
    command: ["sh", "-c", "mkdir -p /data && chmod 777 /data"]

networks:
  default:
    name: homie-dev
